language: python
python:
  - '3.6'

env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2

script:
  - make

deploy:
  # Push code
  - provider: script
    script: aws lambda update-function-code --publish --function-name Get-Gigs --zip-file fileb://dist/zootapi.zip

  # Add configuration
  - provider: script
    script: aws lambda update-function-configuration --function-name Get-Gigs --environment "Variables={RDS_MASTER_USER=RDS_MASTER_USER,RDS_MASTER_PASSWORD=RDS_MASTER_PASSWORD,RDS_DATABASE_NAME=RDS_DATABASE_NAME,RDS_ENDPOINT=RDS_ENDPOINT}"