language: python
python:
  - '3.6'

env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2

script:
  - make

deploy:
  provider: lambda
  runtime: "python3.6"
  region: "ap-southeast-2"
  role: $ROLE_GET_GIGS
  publish: true
  function_name: "Get-Gigs"
  handler_name: "lambda_handler"
  module_name: "zootapi"
  zip: dist/zootapi.zip

  environment_variables:
    - RDS_MASTER_USER=$RDS_MASTER_USER
    - RDS_MASTER_PASSWORD=$RDS_MASTER_PASSWORD
    - RDS_DATABASE_NAME=$RDS_DATABASE_NAME
    - RDS_ENDPOINT=$RDS_ENDPOINT
    
  on:
    branch: master
