service: zoot-api

provider:
  name: aws
  timeout: 30
  runtime: python3.8
  region: ${env:AWS_REGION}
  logs:
    restApi: true
  environment:
    MONGO_USERNAME: ${env:MONGO_USERNAME}
    MONGO_PASSWORD: ${env:MONGO_PASSWORD}
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING}


functions:
  getgigs:
    module: src
    handler: gigs_api.get_gigs
    include:
      - src/**
    events:
      - http:
          path: gigs
          method: get

  addgigs:
    module: src
    handler: gigs_api.add_gigs
    include:
      - src/**
    events:
      - http:
          path: gigs
          method: post

  getvenues:
    module: src
    handler: venues_api.get_venues
    include:
      - src/**
    events:
      - http:
          path: venues
          method: get

  addvenues:
    module: src
    handler: venues_api.add_venue
    include:
      - src/**
    events:
      - http:
          path: venues
          method: post


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
