service: zootapi

frameworkVersion: '2'

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-python-requirements

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      noStart: true
    migration:
      dir: dev/migrations

  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - node_modules/**
    - LICENSE
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt
    - dev/**

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/gigs"

functions:
  create:
    handler: src/api/gigs/gigs.create
    events:
      - http:
          path: gigs/
          method: post
          cors: true
  
  list:
    handler: src/api/gigs/gigs.list
    events:
      - http:
          path: gigs/
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                date: false
                venue: false
                limit: false

resources:
  Resources:
    GigsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: gig_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: gig_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        TableName: gigs
